In [1]:
# from block_group_load_curves import *
# from location_str_to_geoid_mapping import *
# from public_chargers import *
from sklearn.metrics.pairwise import haversine_distances
import folium
from folium.features import GeoJsonTooltip
import pandas as pd
from pathlib import Path
import geopandas as gpd
import numpy as np
import json

In [2]:

# =========================================================
# Find origin and destination energy demand and distances
# =========================================================

DATA_DIR = Path.cwd().parent / "data"

df = pd.read_parquet(DATA_DIR / 'network_analysis/df.parquet')
gdf_subset = pd.read_parquet(DATA_DIR / 'network_analysis/gdf_subset.parquet')
charger_df = pd.read_parquet(DATA_DIR / 'network_analysis/charger_df.parquet')
charger_gdf = gpd.read_parquet(DATA_DIR / 'network_analysis/charger_gdf.parquet')
gdf = gpd.read_parquet(DATA_DIR / 'network_analysis/gdf.parquet')
gdf_for_json = gpd.read_file(DATA_DIR / 'network_analysis/gdf.geojson')

with open((DATA_DIR / 'Geography_Files/location_str_to_geoid_mapping.json'), 'r') as f:
    mapping = json.load(f)

# Flatten column MultiIndex
df.columns = [
    '_'.join(col).strip() if isinstance(col, tuple) else col
    for col in df.columns.values
]

In [3]:

# Merge lat and lon data from GeoPandas df with block group data and map to census track
demand_df = df.merge(gdf_subset, on='geoid_str_', how='left')
# demand_df

In [4]:
gdf_subset.head()

,geoid_str_,INTPTLAT,INTPTLON,NEIGHBOURS
0,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"[1 (Tract 4233, Alameda, CA), 4 (Tract 4231, A..."
1,"1 (Tract 423.36, Orange, CA)",33.545621,-117.699173,"[2 (Tract 423.29, Orange, CA), 2 (Tract 423.19..."
2,"2 (Tract 4043, Alameda, CA)",37.844708,-122.241138,"[2 (Tract 4003, Alameda, CA), 3 (Tract 4043, A..."
3,"1 (Tract 3851, Contra Costa, CA)",37.924964,-122.298942,"[3 (Tract 3901, Contra Costa, CA), 1 (Tract 39..."
4,"2 (Tract 2512, Solano, CA)",38.104862,-122.237457,"[1 (Tract 2510, Solano, CA), 3 (Tract 2512, So..."

In [5]:
print(gdf_subset.columns.tolist())

['geoid_str_', 'INTPTLAT', 'INTPTLON', 'NEIGHBOURS']

In [6]:


# Filter df for data at only 6 pm
demand_df_filtered = demand_df[demand_df['hour_'] == pd.to_timedelta('18:00:00')]

# Drop locations with invalid coordinates
demand_df_filtered = demand_df_filtered.dropna(subset=['INTPTLAT', 'INTPTLON'])

# Take only locations from Alameda County
demand_df_filtered = demand_df_filtered[demand_df_filtered['geoid_str_'].str.contains('Alameda', case=False, na=False)]

# Compute mass
demand_df_filtered['mass'] = demand_df_filtered.loc[:, 'load_curve_MFH_LD_L2':'load_curve_Work_LD_L2'].sum(axis=1)

# Convert to radians for haversine calculation
coords = np.radians(demand_df_filtered[['INTPTLAT', 'INTPTLON']])
dist_matrix = haversine_distances(coords) * 6371

# Change dist matrix from array to pandas df
df_dist = pd.DataFrame(
    dist_matrix,
    columns=demand_df_filtered['geoid_str_'].values
).assign(geoid_str_=demand_df_filtered['geoid_str_'].values)[
    ['geoid_str_'] + demand_df_filtered['geoid_str_'].values.tolist()
]
# Set geo ids as index
df_dist = df_dist.set_index('geoid_str_')

# Map index values to geo id values
index = pd.Series(range(len(df_dist)), index=df_dist.index)

In [7]:
# =========================================================
# Nearest neighbours
# =========================================================

# Take nearest neighbours data from location_str_to_geoid_mapping.py
network_df = gdf_subset.explode('NEIGHBOURS')

# Spatial join of charger location points and census track polygons to categorize each charger
# with its respective census track
charger_loc_gdf = gpd.sjoin(
    charger_gdf,
    gdf[["GEOID_STR", "geometry"]],
    how="left",
    predicate="within"
)
charger_loc_gdf = charger_loc_gdf.drop(columns=["index_right"])
charger_loc_gdf.rename(columns={"GEOID_STR": "geoid_str_"}, inplace=True)

# group chargers by geoid_str_ and aggregate into a list
chargers_per_tract = (
    charger_loc_gdf.groupby("geoid_str_")["ID"]
    .apply(list)
    .reset_index()  # convert back to DataFrame for merging
)

# First merge: origin chargers
network_df = network_df.merge(
    chargers_per_tract,
    how="left",
    left_on="geoid_str_",
    right_on="geoid_str_"
).rename(columns={"ID": "origin_chargers"}) 

# Second merge: destination chargers
network_df = network_df.merge(
    chargers_per_tract,
    how="left",
    left_on="NEIGHBOURS",
    right_on="geoid_str_"
).rename(columns={"ID": "destination_chargers"})

# fix column names
network_df = network_df.drop(columns=["geoid_str__y"])
network_df = network_df.rename(columns={"geoid_str__x": "geoid_str_"})

/var/folders/zv/7h23jkj12tl1zd_4bsx6h9wr0000gn/T/ipykernel_64641/2532565986.py:10: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: None
Right CRS: EPSG:4326

  charger_loc_gdf = gpd.sjoin(

In [8]:
# =========================================================
# Simplify to Alameda County
# =========================================================

# Take only locations from Alameda County
network_df = network_df[network_df['geoid_str_'].str.contains('Alameda', case=False, na=False)]
network_df = network_df[network_df['NEIGHBOURS'].str.contains('Alameda', case=False, na=False)]

# Get demand for each census block
network_df = network_df.merge(demand_df_filtered[['geoid_str_', 'mass']], how='left', on='geoid_str_')
network_df = network_df.rename(columns={'mass':'origin_demand_(kW)'})

# Add destination mass here with df.merge
network_df = pd.merge(network_df, demand_df_filtered[['geoid_str_', 'mass']], left_on='NEIGHBOURS', right_on='geoid_str_', how='left')
network_df = network_df.rename(columns={'mass':'destination_demand_(kW)'})
network_df = network_df.rename(columns={'geoid_str__x': 'geoid_str_'}).drop(columns=['geoid_str__y'])

# Begin Add Haversine distances
# Lookup matrix positions
row_idx = index[network_df['geoid_str_']].values
col_idx = index[network_df['NEIGHBOURS']].values

# Extract distances
network_df['distance_km'] = dist_matrix[row_idx, col_idx]

# Adding location str mapping ids 
network_df['geoid'] = network_df['geoid_str_'].map(mapping)
network_df['neighbor_geoid'] = network_df['NEIGHBOURS'].map(mapping)

network_df.to_parquet(DATA_DIR / 'network_analysis/network_df.parquet')

# =============================================
# End origin-destination analysis
# =============================================

In [9]:
network_df.head()

,geoid_str_,INTPTLAT,INTPTLON,NEIGHBOURS,origin_chargers,destination_chargers,origin_demand_(kW),destination_demand_(kW),distance_km,geoid,neighbor_geoid
0,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"1 (Tract 4233, Alameda, CA)",[333026],NaN,568.288007,274.272001,0.760447,060014232002,060014233001
1,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"4 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,433.504001,0.668007,060014232002,060014231004
2,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"1 (Tract 4220, Alameda, CA)",[333026],"[161015, 205385, 220218, 220219, 308753, 32132...",568.288007,2937.020025,0.823073,060014232002,060014220001
3,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"3 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,178.240000,0.667594,060014232002,060014231003
4,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"2 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,637.020002,0.707463,060014232002,060014231002

### New Section - Calculate travel time and append to network_df

In [10]:
import osmnx as ox
import networkx as nx

print("Loading Alameda County road network...")
G = ox.graph_from_place("Alameda County, California, USA", network_type="drive")
G = ox.speed.add_edge_speeds(G)
G = ox.speed.add_edge_travel_times(G)
print("Network ready.")

Loading Alameda County road network...
Network ready.

In [11]:
#create travel time df of origin destination pairs and respective lat/lon 

tt_df = network_df[['geoid_str_', 'INTPTLAT', 'INTPTLON', 'NEIGHBOURS']].copy()
tt_df.columns = ["orig_geoid_str", "orig_lat", "orig_lon", "dest_geoid_str"]

tt_df = tt_df.merge(
    gdf_subset,
    left_on='dest_geoid_str',  # column in table1
    right_on='geoid_str_',       # column in table2
    how='left'
)

tt_df = tt_df.drop(columns = ["NEIGHBOURS", "geoid_str_"])
tt_df = tt_df.rename(columns={'INTPTLAT': 'dest_lat'})
tt_df = tt_df.rename(columns={'INTPTLON': 'dest_lon'})

In [12]:
# snap OD pair to node on G
tt_df["origin_node"] = ox.distance.nearest_nodes(
    G,
    tt_df["orig_lon"].values,
    tt_df["orig_lat"].values
)

tt_df["dest_node"] = ox.distance.nearest_nodes(
    G,
    tt_df["dest_lon"].values,
    tt_df["dest_lat"].values
)

In [13]:
def compute_tt(row):
    try:
        return nx.shortest_path_length(
            G,
            source=row["origin_node"],
            target=row["dest_node"],
            weight="travel_time"
        )
    except:
        return np.nan  # unreachable

tt_df["travel_time_sec"] = tt_df.apply(compute_tt, axis=1)
tt_df["travel_time_min"] = tt_df["travel_time_sec"] / 60

In [14]:
network_df = network_df.merge(
    tt_df[['orig_geoid_str', 'dest_geoid_str', "travel_time_min", "travel_time_sec"]],
    left_on=['geoid_str_', 'NEIGHBOURS'],  
    right_on=['orig_geoid_str', 'dest_geoid_str'], 
    how='left'                     
)

In [16]:
network_df.head()

,geoid_str_,INTPTLAT,INTPTLON,NEIGHBOURS,origin_chargers,destination_chargers,origin_demand_(kW),destination_demand_(kW),distance_km,geoid,neighbor_geoid,orig_geoid_str,dest_geoid_str,travel_time_min,travel_time_sec
0,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"1 (Tract 4233, Alameda, CA)",[333026],NaN,568.288007,274.272001,0.760447,060014232002,060014233001,"2 (Tract 4232, Alameda, CA)","1 (Tract 4233, Alameda, CA)",1.370000,82.2
1,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"4 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,433.504001,0.668007,060014232002,060014231004,"2 (Tract 4232, Alameda, CA)","4 (Tract 4231, Alameda, CA)",1.253333,75.2
2,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"1 (Tract 4220, Alameda, CA)",[333026],"[161015, 205385, 220218, 220219, 308753, 32132...",568.288007,2937.020025,0.823073,060014232002,060014220001,"2 (Tract 4232, Alameda, CA)","1 (Tract 4220, Alameda, CA)",1.003333,60.2
3,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"3 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,178.240000,0.667594,060014232002,060014231003,"2 (Tract 4232, Alameda, CA)","3 (Tract 4231, Alameda, CA)",1.236667,74.2
4,"2 (Tract 4232, Alameda, CA)",37.862497,-122.293241,"2 (Tract 4231, Alameda, CA)",[333026],NaN,568.288007,637.020002,0.707463,060014232002,060014231002,"2 (Tract 4232, Alameda, CA)","2 (Tract 4231, Alameda, CA)",1.261667,75.7

In [17]:
#sanity check
import geopy.distance

for i, row in tt_df.iterrows():
    dist_km = geopy.distance.distance(
        (row['orig_lat'], row['orig_lon']),
        (row['dest_lat'], row['dest_lon'])
    ).km
    if dist_km > 4: 
        print(i, row['orig_geoid_str'], row['dest_geoid_str'], dist_km)

78 1 (Tract 4100, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 6.883713358397987
126 3 (Tract 4351.03, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 7.563637788115718
222 1 (Tract 4511.02, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 4.648600883013519
291 5 (Tract 4507.01, Alameda, CA) 2 (Tract 4411, Alameda, CA) 14.362873124402572
292 5 (Tract 4507.01, Alameda, CA) 1 (Tract 4506.01, Alameda, CA) 12.998801019854733
293 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4507.01, Alameda, CA) 11.477001264218192
294 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4506.01, Alameda, CA) 13.442027942610233
295 5 (Tract 4507.01, Alameda, CA) 1 (Tract 4507.01, Alameda, CA) 11.330634760446715
296 5 (Tract 4507.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 17.963821267482302
297 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4506.07, Alameda, CA) 12.905647514319236
298 5 (Tract 4507.01, Alameda, CA) 2 (Tract 4507.01, Alameda, CA) 12.70404554796642
299 5 (Tract 4507.01, Alameda, CA) 2 (Tract 4507.42, Alameda, CA) 12.69565067593602
300 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4507.42, Alameda, CA) 13.223449339014632
301 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 17.311371818715287
302 5 (Tract 4507.01, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 11.437267082219758
303 5 (Tract 4507.01, Alameda, CA) 4 (Tract 4507.01, Alameda, CA) 9.993626991712766
304 5 (Tract 4507.01, Alameda, CA) 3 (Tract 4431.03, Alameda, CA) 8.670658487602584
305 5 (Tract 4507.01, Alameda, CA) 1 (Tract 4420, Alameda, CA) 11.626326982888195
306 5 (Tract 4507.01, Alameda, CA) 2 (Tract 4432, Alameda, CA) 11.209945728011196
307 5 (Tract 4507.01, Alameda, CA) 1 (Tract 4432, Alameda, CA) 10.319335562686048
368 2 (Tract 4507.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 12.70404554796642
416 3 (Tract 4081, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 7.65018325135898
439 4 (Tract 4415.03, Alameda, CA) 0 (Tract 9900, Alameda, CA) 23.763268800580065
440 4 (Tract 4415.03, Alameda, CA) 1 (Tract 4371.01, Alameda, CA) 10.127930111291077
444 4 (Tract 4415.03, Alameda, CA) 3 (Tract 4442, Alameda, CA) 4.309509050842381
445 4 (Tract 4415.03, Alameda, CA) 2 (Tract 4415.24, Alameda, CA) 5.492753806135376
446 4 (Tract 4415.03, Alameda, CA) 3 (Tract 4415.03, Alameda, CA) 5.561220955679777
447 4 (Tract 4415.03, Alameda, CA) 1 (Tract 4415.24, Alameda, CA) 6.0053922962238815
448 4 (Tract 4415.03, Alameda, CA) 2 (Tract 4415.01, Alameda, CA) 6.271062566342356
449 4 (Tract 4415.03, Alameda, CA) 3 (Tract 4415.21, Alameda, CA) 6.624421242861159
450 4 (Tract 4415.03, Alameda, CA) 1 (Tract 4415.01, Alameda, CA) 7.0691239795055365
451 4 (Tract 4415.03, Alameda, CA) 4 (Tract 4415.21, Alameda, CA) 7.425987160581083
452 4 (Tract 4415.03, Alameda, CA) 2 (Tract 4403.32, Alameda, CA) 7.8119574649919405
453 4 (Tract 4415.03, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 10.15955784466954
454 4 (Tract 4415.03, Alameda, CA) 2 (Tract 4446.02, Alameda, CA) 5.750309705633569
472 1 (Tract 4324, Alameda, CA) 3 (Tract 4090, Alameda, CA) 4.4249006888563045
536 3 (Tract 4442, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 4.309509050842381
551 2 (Tract 4511.04, Alameda, CA) 1 (Tract 4511.04, Alameda, CA) 8.658187598334568
552 2 (Tract 4511.04, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 16.145004459085534
608 1 (Tract 4220, Alameda, CA) 0 (Tract 9900, Alameda, CA) 20.51082293505177
639 2 (Tract 4443.04, Alameda, CA) 1 (Tract 4443.03, Alameda, CA) 4.477049030792561
664 3 (Tract 4513, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 7.106164002199304
665 3 (Tract 4513, Alameda, CA) 1 (Tract 4507.51, Alameda, CA) 4.20278394658488
666 3 (Tract 4513, Alameda, CA) 1 (Tract 4507.52, Alameda, CA) 5.444262621685537
670 3 (Tract 4513, Alameda, CA) 1 (Tract 4507.50, Alameda, CA) 4.580976296765704
857 3 (Tract 4415.03, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 5.561220955679777
935 2 (Tract 4506.01, Alameda, CA) 3 (Tract 4301.01, Alameda, CA) 6.679910293484537
936 2 (Tract 4506.01, Alameda, CA) 1 (Tract 4506.01, Alameda, CA) 7.5067209393090195
937 2 (Tract 4506.01, Alameda, CA) 3 (Tract 4506.01, Alameda, CA) 6.86506424666711
938 2 (Tract 4506.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 4.351357871915125
939 2 (Tract 4506.01, Alameda, CA) 1 (Tract 4506.08, Alameda, CA) 5.156339672343888
940 2 (Tract 4506.01, Alameda, CA) 3 (Tract 4506.08, Alameda, CA) 4.220063477911157
1156 1 (Tract 4446.02, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 5.84940229368126
1158 3 (Tract 4308, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 7.7574060733602845
1224 1 (Tract 4501.02, Alameda, CA) 1 (Tract 4507.52, Alameda, CA) 5.386514435963547
1250 1 (Tract 4512.02, Alameda, CA) 3 (Tract 4512.02, Alameda, CA) 4.025935392821306
1252 1 (Tract 4512.02, Alameda, CA) 1 (Tract 4511.04, Alameda, CA) 11.765567822155912
1253 1 (Tract 4512.02, Alameda, CA) 1 (Tract 4507.52, Alameda, CA) 5.541107436345158
1254 1 (Tract 4512.02, Alameda, CA) 3 (Tract 4513, Alameda, CA) 7.106164002199304
1255 1 (Tract 4512.02, Alameda, CA) 1 (Tract 4513, Alameda, CA) 5.000523956770672
1256 1 (Tract 4512.02, Alameda, CA) 1 (Tract 4514.01, Alameda, CA) 4.338627073796196
1257 1 (Tract 4512.02, Alameda, CA) 2 (Tract 4514.01, Alameda, CA) 4.2985947095403
1260 1 (Tract 4512.02, Alameda, CA) 4 (Tract 4512.01, Alameda, CA) 4.2508614650236884
1303 3 (Tract 4429, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 4.584801331374644
1338 2 (Tract 4507.42, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 12.69565067593602
1423 4 (Tract 4403.01, Alameda, CA) 1 (Tract 4401, Alameda, CA) 5.017325597085434
1502 1 (Tract 4285, Alameda, CA) 0 (Tract 9900, Alameda, CA) 8.698131404579104
1614 3 (Tract 4506.01, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 6.86506424666711
1615 3 (Tract 4506.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 13.442027942610233
1650 3 (Tract 4372, Alameda, CA) 1 (Tract 4371.01, Alameda, CA) 4.330205489319145
1664 1 (Tract 4401, Alameda, CA) 4 (Tract 4403.01, Alameda, CA) 5.017325597085434
1666 1 (Tract 4401, Alameda, CA) 1 (Tract 4380, Alameda, CA) 4.108640008917146
1667 1 (Tract 4401, Alameda, CA) 1 (Tract 4351.04, Alameda, CA) 5.571724921268033
1674 1 (Tract 4515.04, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 15.144613835051365
1813 2 (Tract 4511.02, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 5.504637285058699
1877 1 (Tract 4081, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 9.852848379058795
1889 4 (Tract 4099, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 6.501891621622924
1925 2 (Tract 4301.01, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 6.631612973299842
1962 4 (Tract 4429, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 5.335257704599163
1969 2 (Tract 4415.03, Alameda, CA) 1 (Tract 4446.02, Alameda, CA) 5.84940229368126
1970 2 (Tract 4415.03, Alameda, CA) 4 (Tract 4429, Alameda, CA) 5.335257704599163
1971 2 (Tract 4415.03, Alameda, CA) 1 (Tract 4428, Alameda, CA) 6.342183316149147
1972 2 (Tract 4415.03, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 10.15955784466954
1973 2 (Tract 4415.03, Alameda, CA) 2 (Tract 4433.01, Alameda, CA) 4.765797172299756
1974 2 (Tract 4415.03, Alameda, CA) 3 (Tract 4433.01, Alameda, CA) 4.409210048793257
1975 2 (Tract 4415.03, Alameda, CA) 1 (Tract 4433.01, Alameda, CA) 4.167455213687616
1980 2 (Tract 4415.03, Alameda, CA) 2 (Tract 4446.02, Alameda, CA) 5.036812437150631
1983 2 (Tract 4415.03, Alameda, CA) 1 (Tract 4430.01, Alameda, CA) 4.39484772560082
1984 2 (Tract 4415.03, Alameda, CA) 3 (Tract 4429, Alameda, CA) 4.584801331374644
2083 2 (Tract 4415.01, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 6.271062566342356
2112 1 (Tract 4507.50, Alameda, CA) 3 (Tract 4513, Alameda, CA) 4.580976296765704
2114 2 (Tract 4501.02, Alameda, CA) 1 (Tract 4507.52, Alameda, CA) 4.056370050954526
2126 3 (Tract 4334, Alameda, CA) 4 (Tract 4371.01, Alameda, CA) 6.095624870831077
2128 3 (Tract 4334, Alameda, CA) 0 (Tract 9900, Alameda, CA) 4.714414235225079
2315 1 (Tract 4513, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 5.000523956770672
2316 1 (Tract 4513, Alameda, CA) 1 (Tract 4507.52, Alameda, CA) 5.080044910646479
2321 3 (Tract 4511.02, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 4.23360743840151
2330 2 (Tract 4505.02, Alameda, CA) 3 (Tract 4301.01, Alameda, CA) 4.256423646992078
2332 2 (Tract 4505.02, Alameda, CA) 1 (Tract 4506.09, Alameda, CA) 4.2641859773895066
2356 3 (Tract 4277, Alameda, CA) 0 (Tract 9900, Alameda, CA) 10.683280589928554
2482 1 (Tract 4284, Alameda, CA) 0 (Tract 9900, Alameda, CA) 8.41765841055378
2491 1 (Tract 4080, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 12.670486875818
2516 3 (Tract 4515.01, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 4.273671991389236
2558 2 (Tract 4203.02, Alameda, CA) 0 (Tract 9900, Alameda, CA) 24.2807229166163
2578 1 (Tract 4512.01, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 15.984090592967311
2668 1 (Tract 4506.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 5.137962417326268
2669 1 (Tract 4506.01, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 7.5067209393090195
2670 1 (Tract 4506.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 12.998801019854733
2714 4 (Tract 4046, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 13.506655487900574
2732 2 (Tract 4351.03, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 5.821888104172747
2747 2 (Tract 4446.02, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 5.750309705633569
2750 2 (Tract 4446.02, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 5.036812437150631
2767 2 (Tract 4251.01, Alameda, CA) 0 (Tract 9900, Alameda, CA) 18.4043079786777
2774 3 (Tract 4415.21, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 6.624421242861159
2856 1 (Tract 4204.02, Alameda, CA) 0 (Tract 9900, Alameda, CA) 23.70243670660621
2857 4 (Tract 4415.21, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 7.425987160581083
2877 3 (Tract 4099, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 7.232267016532052
2879 1 (Tract 4351.03, Alameda, CA) 3 (Tract 4301.01, Alameda, CA) 10.007073723394738
2880 1 (Tract 4351.03, Alameda, CA) 4 (Tract 4301.01, Alameda, CA) 8.550966686563557
2881 1 (Tract 4351.03, Alameda, CA) 3 (Tract 4351.03, Alameda, CA) 7.563637788115718
2882 1 (Tract 4351.03, Alameda, CA) 1 (Tract 4301.01, Alameda, CA) 9.100162809349728
2884 1 (Tract 4351.03, Alameda, CA) 1 (Tract 4351.02, Alameda, CA) 6.495734780990865
2885 1 (Tract 4351.03, Alameda, CA) 2 (Tract 4364.02, Alameda, CA) 6.371589504437206
2886 1 (Tract 4351.03, Alameda, CA) 2 (Tract 4351.03, Alameda, CA) 5.821888104172747
2887 1 (Tract 4351.03, Alameda, CA) 2 (Tract 4411, Alameda, CA) 6.7925231051667
2889 1 (Tract 4351.03, Alameda, CA) 1 (Tract 4506.01, Alameda, CA) 5.137962417326268
2890 1 (Tract 4351.03, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 4.351357871915125
2891 1 (Tract 4351.03, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 17.963821267482302
2952 3 (Tract 4433.01, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 4.409210048793257
2956 2 (Tract 4411, Alameda, CA) 1 (Tract 4403.37, Alameda, CA) 4.400020391793357
2958 2 (Tract 4411, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 6.7925231051667
2959 2 (Tract 4411, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 14.362873124402572
2978 1 (Tract 4380, Alameda, CA) 1 (Tract 4401, Alameda, CA) 4.108640008917146
3000 3 (Tract 4090, Alameda, CA) 4 (Tract 4283.01, Alameda, CA) 4.181897422149838
3001 3 (Tract 4090, Alameda, CA) 3 (Tract 4324, Alameda, CA) 4.340293190646873
3002 3 (Tract 4090, Alameda, CA) 1 (Tract 4324, Alameda, CA) 4.4249006888563045
3137 1 (Tract 9819, Alameda, CA) 0 (Tract 9900, Alameda, CA) 15.038096570063388
3148 2 (Tract 4515.01, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 4.157258005315523
3204 1 (Tract 4506.08, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 5.156339672343888
3292 1 (Tract 4433.01, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 4.167455213687616
3294 0 (Tract 9900, Alameda, CA) 1 (Tract 4204.02, Alameda, CA) 23.70243670660621
3295 0 (Tract 9900, Alameda, CA) 2 (Tract 4203.02, Alameda, CA) 24.2807229166163
3296 0 (Tract 9900, Alameda, CA) 1 (Tract 4220, Alameda, CA) 20.51082293505177
3297 0 (Tract 9900, Alameda, CA) 2 (Tract 4251.01, Alameda, CA) 18.4043079786777
3298 0 (Tract 9900, Alameda, CA) 3 (Tract 4017, Alameda, CA) 17.197039894816026
3299 0 (Tract 9900, Alameda, CA) 1 (Tract 9819, Alameda, CA) 15.038096570063388
3300 0 (Tract 9900, Alameda, CA) 2 (Tract 4287, Alameda, CA) 13.845503101336528
3301 0 (Tract 9900, Alameda, CA) 2 (Tract 4286, Alameda, CA) 9.663582611190277
3302 0 (Tract 9900, Alameda, CA) 3 (Tract 4277, Alameda, CA) 10.683280589928554
3303 0 (Tract 9900, Alameda, CA) 1 (Tract 4284, Alameda, CA) 8.41765841055378
3304 0 (Tract 9900, Alameda, CA) 1 (Tract 4285, Alameda, CA) 8.698131404579104
3305 0 (Tract 9900, Alameda, CA) 4 (Tract 4283.01, Alameda, CA) 6.174917894218246
3308 0 (Tract 9900, Alameda, CA) 3 (Tract 4334, Alameda, CA) 4.714414235225079
3309 0 (Tract 9900, Alameda, CA) 4 (Tract 4371.01, Alameda, CA) 8.918571071222784
3310 0 (Tract 9900, Alameda, CA) 1 (Tract 4371.01, Alameda, CA) 14.406374236776522
3311 0 (Tract 9900, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 23.763268800580065
3314 3 (Tract 4507.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 11.477001264218192
3405 4 (Tract 4512.01, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 4.2508614650236884
3476 1 (Tract 4415.24, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 6.0053922962238815
3552 3 (Tract 4512.02, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 4.025935392821306
3553 3 (Tract 4512.02, Alameda, CA) 1 (Tract 4511.04, Alameda, CA) 9.012506666185228
3556 1 (Tract 4432, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 10.319335562686048
3584 2 (Tract 4433.01, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 4.765797172299756
3632 1 (Tract 4351.04, Alameda, CA) 1 (Tract 4401, Alameda, CA) 5.571724921268033
3651 2 (Tract 4287, Alameda, CA) 0 (Tract 9900, Alameda, CA) 13.845503101336528
3696 1 (Tract 4371.01, Alameda, CA) 4 (Tract 4371.01, Alameda, CA) 6.013555017946792
3697 1 (Tract 4371.01, Alameda, CA) 0 (Tract 9900, Alameda, CA) 14.406374236776522
3705 1 (Tract 4371.01, Alameda, CA) 3 (Tract 4372, Alameda, CA) 4.330205489319145
3706 1 (Tract 4371.01, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 10.127930111291077
3757 1 (Tract 4507.52, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 5.541107436345158
3759 1 (Tract 4507.52, Alameda, CA) 2 (Tract 4501.02, Alameda, CA) 4.056370050954526
3760 1 (Tract 4507.52, Alameda, CA) 1 (Tract 4501.02, Alameda, CA) 5.386514435963547
3763 1 (Tract 4507.52, Alameda, CA) 3 (Tract 4513, Alameda, CA) 5.444262621685537
3764 1 (Tract 4507.52, Alameda, CA) 1 (Tract 4513, Alameda, CA) 5.080044910646479
3865 2 (Tract 4286, Alameda, CA) 0 (Tract 9900, Alameda, CA) 9.663582611190277
3897 2 (Tract 4364.02, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 6.371589504437206
3918 1 (Tract 4415.01, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 7.0691239795055365
3940 3 (Tract 4506.08, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 4.220063477911157
4103 2 (Tract 4403.32, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 7.8119574649919405
4373 1 (Tract 4514.01, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 4.338627073796196
4405 4 (Tract 4301.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 8.550966686563557
4433 3 (Tract 4431.03, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 8.670658487602584
4439 3 (Tract 4431.03, Alameda, CA) 1 (Tract 4420, Alameda, CA) 4.749701767394457
4489 1 (Tract 4301.01, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 7.684012091871778
4496 1 (Tract 4301.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 9.100162809349728
4544 2 (Tract 4090, Alameda, CA) 4 (Tract 4283.01, Alameda, CA) 4.136677285040706
4547 2 (Tract 4511.03, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 11.437267082219758
4548 2 (Tract 4511.03, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 10.854190213544536
4549 2 (Tract 4511.03, Alameda, CA) 4 (Tract 4507.01, Alameda, CA) 7.291486601303465
4550 2 (Tract 4511.03, Alameda, CA) 2 (Tract 4511.02, Alameda, CA) 5.504637285058699
4551 2 (Tract 4511.03, Alameda, CA) 3 (Tract 4511.02, Alameda, CA) 4.23360743840151
4552 2 (Tract 4511.03, Alameda, CA) 1 (Tract 4511.02, Alameda, CA) 4.648600883013519
4554 2 (Tract 4511.03, Alameda, CA) 3 (Tract 4516.01, Alameda, CA) 4.684158119253071
4555 2 (Tract 4511.03, Alameda, CA) 2 (Tract 4515.01, Alameda, CA) 4.157258005315523
4556 2 (Tract 4511.03, Alameda, CA) 3 (Tract 4515.01, Alameda, CA) 4.273671991389236
4557 2 (Tract 4511.03, Alameda, CA) 1 (Tract 4511.03, Alameda, CA) 6.334924076513647
4646 1 (Tract 4507.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 11.330634760446715
4746 2 (Tract 4304, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 6.831377914878462
4765 2 (Tract 4415.24, Alameda, CA) 4 (Tract 4415.03, Alameda, CA) 5.492753806135376
4796 4 (Tract 4507.01, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 9.993626991712766
4797 4 (Tract 4507.01, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 7.291486601303465
4856 2 (Tract 4080, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 12.231167358784527
4880 3 (Tract 4324, Alameda, CA) 3 (Tract 4090, Alameda, CA) 4.340293190646873
5008 2 (Tract 4514.01, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 4.2985947095403
5264 1 (Tract 4303, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 6.141742210133142
5270 3 (Tract 4516.01, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 4.684158119253071
5307 1 (Tract 4505.02, Alameda, CA) 3 (Tract 4301.01, Alameda, CA) 5.364901763876683
5319 1 (Tract 4511.04, Alameda, CA) 3 (Tract 4512.02, Alameda, CA) 9.012506666185228
5320 1 (Tract 4511.04, Alameda, CA) 2 (Tract 4512.02, Alameda, CA) 8.74812465055044
5321 1 (Tract 4511.04, Alameda, CA) 1 (Tract 4512.02, Alameda, CA) 11.765567822155912
5322 1 (Tract 4511.04, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 18.375234563526803
5323 1 (Tract 4511.04, Alameda, CA) 2 (Tract 4511.04, Alameda, CA) 8.658187598334568
5346 1 (Tract 4351.02, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 6.495734780990865
5376 4 (Tract 4283.01, Alameda, CA) 3 (Tract 4090, Alameda, CA) 4.181897422149838
5379 4 (Tract 4283.01, Alameda, CA) 2 (Tract 4073, Alameda, CA) 4.630826156961723
5388 4 (Tract 4283.01, Alameda, CA) 2 (Tract 4090, Alameda, CA) 4.136677285040706
5389 4 (Tract 4283.01, Alameda, CA) 0 (Tract 9900, Alameda, CA) 6.174917894218246
5447 1 (Tract 4443.03, Alameda, CA) 2 (Tract 4443.04, Alameda, CA) 4.477049030792561
5615 4 (Tract 4371.01, Alameda, CA) 3 (Tract 4334, Alameda, CA) 6.095624870831077
5627 4 (Tract 4371.01, Alameda, CA) 0 (Tract 9900, Alameda, CA) 8.918571071222784
5628 4 (Tract 4371.01, Alameda, CA) 1 (Tract 4371.01, Alameda, CA) 6.013555017946792
5941 1 (Tract 4403.37, Alameda, CA) 2 (Tract 4411, Alameda, CA) 4.400020391793357
5973 3 (Tract 4511.04, Alameda, CA) 1 (Tract 4511.04, Alameda, CA) 18.375234563526803
5974 3 (Tract 4511.04, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 17.311371818715287
5975 3 (Tract 4511.04, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 10.854190213544536
5976 3 (Tract 4511.04, Alameda, CA) 1 (Tract 4511.03, Alameda, CA) 12.992854127780047
5977 3 (Tract 4511.04, Alameda, CA) 1 (Tract 4515.04, Alameda, CA) 15.144613835051365
5978 3 (Tract 4511.04, Alameda, CA) 1 (Tract 4512.01, Alameda, CA) 15.984090592967311
5979 3 (Tract 4511.04, Alameda, CA) 2 (Tract 4511.04, Alameda, CA) 16.145004459085534
6077 3 (Tract 4017, Alameda, CA) 0 (Tract 9900, Alameda, CA) 17.197039894816026
6097 1 (Tract 4511.03, Alameda, CA) 3 (Tract 4511.04, Alameda, CA) 12.992854127780047
6098 1 (Tract 4511.03, Alameda, CA) 2 (Tract 4511.03, Alameda, CA) 6.334924076513647
6114 1 (Tract 4428, Alameda, CA) 2 (Tract 4415.03, Alameda, CA) 6.342183316149147
6220 3 (Tract 4301.01, Alameda, CA) 1 (Tract 4301.02, Alameda, CA) 5.302771892414654
6221 3 (Tract 4301.01, Alameda, CA) 1 (Tract 4505.02, Alameda, CA) 5.364901763876683
6224 3 (Tract 4301.01, Alameda, CA) 1 (Tract 4351.03, Alameda, CA) 10.007073723394738
6225 3 (Tract 4301.01, Alameda, CA) 2 (Tract 4506.01, Alameda, CA) 6.679910293484537
6226 3 (Tract 4301.01, Alameda, CA) 2 (Tract 4505.02, Alameda, CA) 4.256423646992078
6270 3 (Tract 4506.07, Alameda, CA) 5 (Tract 4507.01, Alameda, CA) 12.905647514319236